apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapport-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapport-service
  template:
    metadata:
      labels:
        app: rapport-service
    spec:
      containers:
        - name: rapport-service
          image: rapport-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: DISCOVERY_SERVICE_URL
              value: http://discovery-service.default.svc.cluster.local:8761/eureka


          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
---
apiVersion: v1
kind: Service
metadata:
  name: rapport-service
spec:
  selector:
    app: rapport-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer