apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: 'employe_service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['employe-service:8081']
            labels:
              application: 'Employe Service'

      - job_name: 'administrateur_service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['administrateur-service:8087']
            labels:
              application: 'Administrateur Service'

      - job_name: 'pointage_service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['pointage-service:8083']
            labels:
              application: 'Pointage Service'

      - job_name: 'anomalie_service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['anomalie-service:8086']
            labels:
              application: 'Anomalie Service'

      - job_name: 'horaire_service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['horaire-service:8084']
            labels:
              application: 'Horaire Service'

      - job_name: 'rapport_service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['rapport-service:8085']
            labels:
              application: 'Rapport Service'

      - job_name: 'conge_service'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['conge-service:8089']
            labels:
              application: 'Conge Service'

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-service
  template:
    metadata:
      labels:
        app: prometheus-service
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus-service
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 9090
  type: LoadBalancer
